packages/curl.cmake: Ignore error implicit func
My forked repository of mpv-winbuild failed to build because it was calling undeclared function 'ASN1_STRING_get_length'. So I applied to ignore error implicit function declaration.

Here is error output before fix:

```
FAILED: [code=1] lib/CMakeFiles/libcurl_object.dir/vtls/openssl.c.obj
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/clang_root/bin/x86_64-w64-mingw32-gcc --sysroot=/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/install/x86_64-w64-mingw32 -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -DCURL_STATICLIB -DHAVE_CONFIG_H -DUNICODE -D_UNICODE -I/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/include -I/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/packages/curl-prefix/src/curl-build/lib -I/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib -DNGHTTP3_STATICLIB -DNGHTTP2_STATICLIB -DNGTCP2_STATICLIB -lz -lbrotlienc -lbrotlidec -lbrotlicommon -lzstd -lcrypt32 -lsecur32 -O3 -DNDEBUG -municode -Werror-implicit-function-declaration -Wextra -Wall -Wpedantic -Wbad-function-cast -Wconversion -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-padded -Wno-sign-conversion -Wno-switch-default -Wno-switch-enum -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wconditional-uninitialized -Wno-used-but-marked-unused -Wshift-sign-overflow -Wshorten-64-to-32 -Wformat=2 -Wlanguage-extension-token -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wformat-non-iso -Wenum-conversion -Wmissing-variable-declarations -Wno-documentation-unknown-command -Wsometimes-uninitialized -Wdouble-promotion -Wheader-guard -Wpragmas -Wunused-const-variable -Wcomma -Wassign-enum -Wextra-semi-stmt -Wimplicit-fallthrough -Wxor-used-as-pow -Wcast-function-type -Wreserved-identifier -Wno-reserved-macro-identifier -Wno-unsafe-buffer-usage -Wcast-function-type-strict -Wformat-signedness -Warray-compare -Wc++-hidden-decl -Wimplicit-int-enum-cast -Wjump-misses-init -Wno-implicit-void-ptr-cast -Wtentative-definition-compat -Wno-c++-keyword -fvisibility=hidden -I/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/install/x86_64-w64-mingw32/include -DLIBSSH_STATIC -DCARES_STATICLIB -DPSL_STATIC -MD -MT lib/CMakeFiles/libcurl_object.dir/vtls/openssl.c.obj -MF lib/CMakeFiles/libcurl_object.dir/vtls/openssl.c.obj.d -o lib/CMakeFiles/libcurl_object.dir/vtls/openssl.c.obj -c /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib/vtls/openssl.c
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib/vtls/openssl.c:432:29: error: call to undeclared function 'ASN1_STRING_get_length'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  432 |       const size_t numlen = ASN1_STRING_get_length(num);
      |                             ^
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib/vtls/openssl.c:507:30: error: call to undeclared function 'ASN1_STRING_get_length'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  507 |       const size_t psiglen = ASN1_STRING_get_length(psig);
      |                              ^
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib/vtls/openssl.c:2098:25: error: call to undeclared function 'ASN1_STRING_get_length'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2098 |         size_t altlen = ASN1_STRING_get_length(check->d.ia5);
      |                         ^
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/curl/lib/vtls/openssl.c:2169:19: error: call to undeclared function 'ASN1_STRING_get_length'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2169 |           cnlen = ASN1_STRING_get_length(tmp);
      |                   ^
4 errors generated.
```

- 2026 Martin Eesmaa